api_i18n_translations_list:
    path: /i18n/{page}
    methods: [GET]
    defaults:
        _controller: prestashop.core.api.i18n.controller:listTranslationAction

api_i18n_domain_list:
    path: /i18n/{locale}/{domain}
    methods: [GET]
    defaults:
        _controller: prestashop.core.api.i18n.controller:listDomainTranslationAction
